
/*
  Translation automatically generated by Archsat
  Input file: 17_16.zf
*/

%-- File './tarski.zf', line 3, character 0-17
tff(decl_1, type, ( point : $tType ) ).

%-- File './tarski.zf', line 4, character 0-42
tff(decl_2, type, ( bet : ( point * point * point ) > $o ) ).

%-- File './tarski.zf', line 5, character 0-52
tff(decl_3, type, ( cong : ( point * point * point * point ) > $o ) ).

%-- File './tarski.zf', line 6, character 0-15
tff(decl_4, type, ( p_A : point ) ).

%-- File './tarski.zf', line 7, character 0-15
tff(decl_5, type, ( p_B : point ) ).

%-- File './tarski.zf', line 8, character 0-15
tff(decl_6, type, ( p_C : point ) ).

%-- File './tarski.zf', line 10, character 0-42
tff(hyp_1, axiom, (! [A: point , B: point] : cong(A, B, B, A))).

%-- File './tarski.zf', line 11, character 0-81
tff(hyp_2, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (cong(A, B, C, D) => (cong(A, B, E, F) => cong(C, D, E, F))))).

%-- File './tarski.zf', line 12, character 0-53
tff(hyp_3, axiom,
    (! [A: point , B: point , C: point] : (cong(A, B, C, C) => (A = B)))).

%-- File './tarski.zf', line 13, character 0-78
tff(hyp_4, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (? [E: point] : (bet(A, B, E) & cong(B, E, C, D))))).

%-- File './tarski.zf', line 14, character 0-169
tff(hyp_5, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (cong(A, B, A1, B1)
       => (cong(B, C, B1, C1)
          => (cong(A, D, A1, D1)
             => (cong(B, D, B1, D1)
                => (bet(A, B, C)
                   => (bet(A1, B1, C1)
                      => ((~ (A = B)) => cong(C, D, C1, D1)))))))))).

%-- File './tarski.zf', line 15, character 0-46
tff(hyp_6, axiom, (! [A: point , B: point] : (bet(A, B, A) => (A = B)))).

%-- File './tarski.zf', line 16, character 0-105
tff(hyp_7, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (bet(A, P, C)
       => (bet(B, Q, C) => (? [X: point] : (bet(P, X, B) & bet(Q, X, A))))))).

%-- File './tarski.zf', line 18, character 0-56
tff(hyp_8, axiom,
    (~ (bet(p_A, p_B, p_C) | (bet(p_B, p_C, p_A) | bet(p_C, p_A, p_B))))).

%-- File './tarski.zf', line 19, character 0-127
tff(hyp_9, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (cong(A, P, A, Q)
       => (cong(B, P, B, Q)
          => (cong(C, P, C, Q)
             => ((~ (P = Q))
                => (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B))))))))).

%-- File './tarski.zf', line 20, character 0-127
tff(hyp_10, axiom,
    (! [A: point , B: point , C: point , D: point , T: point] :
       (? [X: point , Y: point] :
          (bet(A, D, T)
          => (bet(B, D, C)
             => ((~ (A = D))
                => (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y))))))))).

%-- File './tarski.zf', line 22, character 0-41
tff(hyp_11, axiom, (! [A: point , B: point] : ((A = B) | (~ (A = B))))).

%-- File './tarski_def.zf', line 5, character 0-42
tff(decl_7, type, ( col : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 6, character 0-88
tff(decl_8, type, (
    ofsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 7, character 0-72
tff(decl_9, type, (
    cong_3 : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 8, character 0-45
tff(decl_10, type, ( bet_4 : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 9, character 0-37
tff(decl_11, type, ( betS : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 10, character 0-88
tff(decl_12, type, (
    ifsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 11, character 0-87
tff(decl_13, type, (
    fsc : ( point * point * point * point * point * point * point * point ) >
          $o ) ).

%-- File './tarski_def.zf', line 12, character 0-42
tff(decl_14, type, ( le : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 13, character 0-42
tff(decl_15, type, ( lt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 14, character 0-42
tff(decl_16, type, ( ge : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 15, character 0-42
tff(decl_17, type, ( gt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 16, character 0-36
tff(decl_18, type, ( out : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 17, character 0-41
tff(decl_19, type, ( midpoint : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 18, character 0-36
tff(decl_20, type, ( per : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 19, character 0-54
tff(decl_21, type, (
    perp_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 20, character 0-44
tff(decl_22, type, ( perp : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 21, character 0-42
tff(decl_23, type, ( ts : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 22, character 0-41
tff(decl_24, type, ( reflectP : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 23, character 0-42
tff(decl_25, type, ( os : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 24, character 0-47
tff(decl_26, type, ( inAngle : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 25, character 0-48
tff(decl_27, type, ( coplanar : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 26, character 0-58
tff(decl_28, type, (
    reflectL_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 27, character 0-48
tff(decl_29, type, ( reflectL : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 28, character 0-47
tff(decl_30, type, ( reflect : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 29, character 0-59
tff(decl_31, type, (
    congA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 30, character 0-57
tff(decl_32, type, (
    leA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 31, character 0-57
tff(decl_33, type, (
    ltA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 32, character 0-57
tff(decl_34, type, (
    gtA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 33, character 0-38
tff(decl_35, type, ( acute : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 34, character 0-39
tff(decl_36, type, ( obtuse : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 35, character 0-57
tff(decl_37, type, (
    geA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 36, character 0-43
tff(decl_38, type, ( par : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 37, character 0-50
tff(decl_39, type, ( par_strict : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 38, character 0-52
tff(decl_40, type, (
    inter : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 39, character 0-39
tff(decl_41, type, ( tarski_s_parallel_postulate : $o ) ).

%-- File './tarski_def.zf', line 40, character 0-40
tff(decl_42, type, ( decidability_of_intersection : $o ) ).

%-- File './tarski_def.zf', line 41, character 0-79
tff(decl_43, type, (
    sumA : ( point * point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 42, character 0-61
tff(decl_44, type, (
    triSumA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 43, character 0-58
tff(decl_45, type, (
    sams : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 44, character 0-48
tff(decl_46, type, ( saccheri : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 45, character 0-56
tff(decl_47, type, ( hypothesis_of_obtuse_saccheri_quadrilaterals : $o ) ).

%-- File './tarski_def.zf', line 51, character 0 to line 52, character 105
tff(hyp_12, axiom,
    (! [A: point , B: point , C: point] :
       (acute(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & ltA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 58, character 0 to line 59, character 114
tff(hyp_13, axiom,
    (! [A1: point , A2: point , A3: point , A4: point] :
       (bet_4(A1, A2, A3, A4)
       <=> (bet(A1, A2, A3)
           & (bet(A2, A3, A4) & (bet(A1, A3, A4) & bet(A1, A2, A4))))))).

%-- File './tarski_def.zf', line 62, character 0 to line 63, character 66
tff(hyp_14, axiom,
    (! [A: point , B: point , C: point] :
       (betS(A, B, C) <=> (bet(A, B, C) & ((~ (A = B)) & (~ (B = C))))))).

%-- File './tarski_def.zf', line 68, character 0 to line 69, character 75
tff(hyp_15, axiom,
    (! [A: point , B: point , C: point] :
       (col(A, B, C) <=> (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B)))))).

%-- File './tarski_def.zf', line 72, character 0 to line 73, character 111
tff(hyp_16, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1)
       <=> (cong(A, B, A1, B1) & (cong(A, C, A1, C1) & cong(B, C, B1, C1)))))).

%-- File './tarski_def.zf', line 77, character 0 to line 78, character 260
tff(hyp_17, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (congA(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (D = E))
               & ((~ (F = E))
                 & (? [A1: point , C1: point , D1: point , F1: point] :
                      (bet(B, A, A1)
                      & (cong(A, A1, E, D)
                        & (bet(B, C, C1)
                          & (cong(C, C1, E, F)
                            & (bet(E, D, D1)
                              & (cong(D, D1, B, A)
                                & (bet(E, F, F1)
                                  & (cong(F, F1, B, C)
                                    & cong(A1, C1, D1, F1))))))))))))))))).

%-- File './tarski_def.zf', line 81, character 0 to line 82, character 151
tff(hyp_18, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (coplanar(A, B, C, D)
       <=> (? [X: point] :
              ((col(A, B, X) & col(C, D, X))
              | ((col(A, C, X) & col(B, D, X))
                | (col(A, D, X) & col(B, C, X)))))))).

%-- File './tarski_def.zf', line 88, character 0 to line 89, character 138
tff(hyp_19, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (fsc(A, B, C, D, A1, B1, C1, D1)
       <=> (col(A, B, C)
           & (cong_3(A, B, C, A1, B1, C1)
             & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))).

%-- File './tarski_def.zf', line 94, character 0 to line 95, character 53
tff(hyp_20, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (ge(A, B, C, D) <=> le(C, D, A, B)))).

%-- File './tarski_def.zf', line 98, character 0 to line 99, character 53
tff(hyp_21, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (gt(A, B, C, D) <=> lt(C, D, A, B)))).

%-- File './tarski_def.zf', line 102, character 0 to line 103, character 67
tff(hyp_22, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (geA(A, B, C, D, E, F) <=> leA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 106, character 0 to line 107, character 67
tff(hyp_23, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (gtA(A, B, C, D, E, F) <=> ltA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 112, character 0 to line 113, character 166
tff(hyp_24, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ifsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, C, A1, C1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(C, D, C1, D1))))))))).

%-- File './tarski_def.zf', line 116, character 0 to line 117, character 127
tff(hyp_25, axiom,
    (! [P: point , A: point , B: point , C: point] :
       (inAngle(P, A, B, C)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (P = B))
               & (? [X: point] : (bet(A, X, C) & ((X = B) | out(B, X, P)))))))))).

%-- File './tarski_def.zf', line 120, character 0 to line 121, character 137
tff(hyp_26, axiom,
    (! [A1: point , A2: point , B1: point , B2: point , X: point] :
       (inter(A1, A2, B1, B2, X)
       <=> ((? [P: point] : (col(P, B1, B2) & (~ col(P, A1, A2))))
           & (col(A1, A2, X) & col(B1, B2, X)))))).

%-- File './tarski_def.zf', line 129, character 0 to line 130, character 90
tff(hyp_27, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (le(A, B, C, D)
       <=> (? [E: point] : (bet(C, E, D) & cong(A, B, C, E)))))).

%-- File './tarski_def.zf', line 133, character 0 to line 134, character 70
tff(hyp_28, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (lt(A, B, C, D) <=> (le(A, B, C, D) & (~ cong(A, B, C, D)))))).

%-- File './tarski_def.zf', line 137, character 0 to line 138, character 110
tff(hyp_29, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (leA(A, B, C, D, E, F)
       <=> (? [P: point] : (inAngle(P, D, E, F) & congA(A, B, C, D, E, P)))))).

%-- File './tarski_def.zf', line 141, character 0 to line 142, character 91
tff(hyp_30, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (ltA(A, B, C, D, E, F)
       <=> (leA(A, B, C, D, E, F) & (~ congA(A, B, C, D, E, F)))))).

%-- File './tarski_def.zf', line 148, character 0 to line 149, character 70
tff(hyp_31, axiom,
    (! [M: point , A: point , B: point] :
       (midpoint(M, A, B) <=> (bet(A, M, B) & cong(A, M, M, B))))).

%-- File './tarski_def.zf', line 155, character 0 to line 156, character 106
tff(hyp_32, axiom,
    (! [A: point , B: point , C: point] :
       (obtuse(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & gtA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 159, character 0 to line 160, character 166
tff(hyp_33, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ofsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, B, A1, B1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))))).

%-- File './tarski_def.zf', line 163, character 0 to line 164, character 89
tff(hyp_34, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (os(A, B, P, Q)
       <=> (? [R: point] : (ts(A, B, P, R) & ts(A, B, Q, R)))))).

%-- File './tarski_def.zf', line 167, character 0 to line 168, character 80
tff(hyp_35, axiom,
    (! [P: point , A: point , B: point] :
       (out(P, A, B)
       <=> ((~ (A = P)) & ((~ (B = P)) & (bet(P, A, B) | bet(P, B, A))))))).

%-- File './tarski_def.zf', line 173, character 0 to line 174, character 132
tff(hyp_36, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par_strict(A, B, C, D)
       <=> ((~ (A = B))
           & ((~ (C = D))
             & (coplanar(A, B, C, D)
               & (~ (? [X: point] : (col(X, A, B) & col(X, C, D)))))))))).

%-- File './tarski_def.zf', line 177, character 0 to line 178, character 107
tff(hyp_37, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par(A, B, C, D)
       <=> (par_strict(A, B, C, D)
           | ((~ (A = B)) & ((~ (C = D)) & (col(A, C, D) & col(B, C, D)))))))).

%-- File './tarski_def.zf', line 181, character 0 to line 182, character 95
tff(hyp_38, axiom,
    (! [A: point , B: point , C: point] :
       (per(A, B, C)
       <=> (? [C1: point] : (midpoint(B, C, C1) & cong(A, C, A, C1)))))).

%-- File './tarski_def.zf', line 185, character 0 to line 186, character 155
tff(hyp_39, axiom,
    (! [X: point , A: point , B: point , C: point , D: point] :
       (perp_at(X, A, B, C, D)
       <=> ((! [U: point , V: point] :
               (col(U, A, B) => (col(V, C, D) => per(U, X, V))))
           & ((~ (A = B)) & ((~ (C = D)) & (col(X, A, B) & col(X, C, D)))))))).

%-- File './tarski_def.zf', line 189, character 0 to line 190, character 84
tff(hyp_40, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (perp(A, B, C, D) <=> (? [X: point] : perp_at(X, A, B, C, D))))).

%-- File './tarski_def.zf', line 197, character 0 to line 198, character 62
tff(hyp_41, axiom,
    (! [A: point , A1: point , C: point] :
       (reflectP(A, A1, C) <=> midpoint(C, A1, A)))).

%-- File './tarski_def.zf', line 201, character 0 to line 202, character 115
tff(hyp_42, axiom,
    (! [M: point , P1: point , P: point , A: point , B: point] :
       (reflectL_at(M, P1, P, A, B)
       <=> (midpoint(M, P, P1) & col(A, B, M)
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 205, character 0 to line 206, character 128
tff(hyp_43, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflectL(P1, P, A, B)
       <=> ((? [X: point] : (midpoint(X, P, P1) & col(A, B, X)))
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 209, character 0 to line 210, character 106
tff(hyp_44, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflect(P1, P, A, B)
       <=> (((~ (A = B)) & reflectL(P1, P1, A, B))
           | ((A = B) & midpoint(A, P, P1)))))).

%-- File './tarski_def.zf', line 215, character 0 to line 216, character 140
tff(hyp_45, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point , G:
       point , H: point , I: point] :
       (sumA(A, B, C, D, E, F, G, H, I)
       <=> (? [J: point] :
              (congA(C, B, J, D, E, F)
              & ((~ os(B, C, A, J)) & congA(A, B, J, G, H, I))))))).

%-- File './tarski_def.zf', line 220, character 0 to line 221, character 101
tff(hyp_46, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (saccheri(A, B, C, D)
       <=> (per(B, A, D)
           & (per(A, D, C) & (cong(A, B, C, D) & os(A, D, B, C))))))).

%-- File './tarski_def.zf', line 224, character 0 to line 225, character 159
tff(hyp_47, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (sams(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((out(E, D, F) | (~ bet(A, B, C)))
             & (? [J: point] :
                  (congA(C, B, J, D, E, F)
                  & ((~ os(B, C, A, J)) & (~ ts(A, B, C, J)))))))))).

%-- File './tarski_def.zf', line 231, character 0 to line 232, character 130
tff(hyp_48, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (triSumA(A, B, C, D, E, F)
       <=> (? [G: point , H: point , I: point] :
              (sumA(A, B, C, B, C, A, G, H, I)
              & sumA(G, H, I, C, A, B, D, E, F)))))).

%-- File './tarski_def.zf', line 235, character 0 to line 236, character 115
tff(hyp_49, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (ts(A, B, P, Q)
       <=> ((~ col(P, A, B))
           & ((~ col(Q, A, B))
             & (? [T: point] : (col(T, A, B) & bet(P, T, Q)))))))).

%-- File './tarski_def.zf', line 241, character 0 to line 242, character 157
tff(hyp_50, axiom,
    (tarski_s_parallel_postulate
    <=> (! [A: point , B: point , C: point , D: point , T: point] :
           (bet(A, D, T)
           => (bet(B, C, D)
              => ((~ (A = D))
                 => (? [X: point , Y: point] :
                       (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y)))))))))).

%-- File './tarski_def.zf', line 244, character 0 to line 245, character 156
tff(hyp_51, axiom,
    (decidability_of_intersection
    <=> (! [A: point , B: point , C: point , D: point] :
           ((? [I: point] : (col(I, A, B) & col(I, C, D)))
           | (~ (? [I: point] : (col(I, A, B) & col(I, C, D)))))))).

%-- File './tarski_def.zf', line 247, character 0 to line 248, character 111
tff(hyp_52, axiom,
    (hypothesis_of_obtuse_saccheri_quadrilaterals
    <=> (! [A: point , B: point , C: point , D: point] :
           (saccheri(A, B, C, D) => obtuse(A, B, C))))).

%-- File './tarski.zf', line 3, character 0-17
tff(decl_48, type, ( point : $tType ) ).

%-- File './tarski.zf', line 4, character 0-42
tff(decl_49, type, ( bet : ( point * point * point ) > $o ) ).

%-- File './tarski.zf', line 5, character 0-52
tff(decl_50, type, ( cong : ( point * point * point * point ) > $o ) ).

%-- File './tarski.zf', line 6, character 0-15
tff(decl_51, type, ( p_A_1 : point ) ).

%-- File './tarski.zf', line 7, character 0-15
tff(decl_52, type, ( p_B_1 : point ) ).

%-- File './tarski.zf', line 8, character 0-15
tff(decl_53, type, ( p_C_1 : point ) ).

%-- File './tarski.zf', line 10, character 0-42
tff(hyp_53, axiom, (! [A: point , B: point] : cong(A, B, B, A))).

%-- File './tarski.zf', line 11, character 0-81
tff(hyp_54, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (cong(A, B, C, D) => (cong(A, B, E, F) => cong(C, D, E, F))))).

%-- File './tarski.zf', line 12, character 0-53
tff(hyp_55, axiom,
    (! [A: point , B: point , C: point] : (cong(A, B, C, C) => (A = B)))).

%-- File './tarski.zf', line 13, character 0-78
tff(hyp_56, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (? [E: point] : (bet(A, B, E) & cong(B, E, C, D))))).

%-- File './tarski.zf', line 14, character 0-169
tff(hyp_57, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (cong(A, B, A1, B1)
       => (cong(B, C, B1, C1)
          => (cong(A, D, A1, D1)
             => (cong(B, D, B1, D1)
                => (bet(A, B, C)
                   => (bet(A1, B1, C1)
                      => ((~ (A = B)) => cong(C, D, C1, D1)))))))))).

%-- File './tarski.zf', line 15, character 0-46
tff(hyp_58, axiom, (! [A: point , B: point] : (bet(A, B, A) => (A = B)))).

%-- File './tarski.zf', line 16, character 0-105
tff(hyp_59, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (bet(A, P, C)
       => (bet(B, Q, C) => (? [X: point] : (bet(P, X, B) & bet(Q, X, A))))))).

%-- File './tarski.zf', line 18, character 0-56
tff(hyp_60, axiom,
    (~
    (bet(p_A_1, p_B_1, p_C_1)
    | (bet(p_B_1, p_C_1, p_A_1) | bet(p_C_1, p_A_1, p_B_1))))).

%-- File './tarski.zf', line 19, character 0-127
tff(hyp_61, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (cong(A, P, A, Q)
       => (cong(B, P, B, Q)
          => (cong(C, P, C, Q)
             => ((~ (P = Q))
                => (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B))))))))).

%-- File './tarski.zf', line 20, character 0-127
tff(hyp_62, axiom,
    (! [A: point , B: point , C: point , D: point , T: point] :
       (? [X: point , Y: point] :
          (bet(A, D, T)
          => (bet(B, D, C)
             => ((~ (A = D))
                => (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y))))))))).

%-- File './tarski.zf', line 22, character 0-41
tff(hyp_63, axiom, (! [A: point , B: point] : ((A = B) | (~ (A = B))))).

%-- File './tarski_def.zf', line 5, character 0-42
tff(decl_54, type, ( col : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 6, character 0-88
tff(decl_55, type, (
    ofsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 7, character 0-72
tff(decl_56, type, (
    cong_3 : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 8, character 0-45
tff(decl_57, type, ( bet_4 : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 9, character 0-37
tff(decl_58, type, ( betS : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 10, character 0-88
tff(decl_59, type, (
    ifsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 11, character 0-87
tff(decl_60, type, (
    fsc : ( point * point * point * point * point * point * point * point ) >
          $o ) ).

%-- File './tarski_def.zf', line 12, character 0-42
tff(decl_61, type, ( le : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 13, character 0-42
tff(decl_62, type, ( lt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 14, character 0-42
tff(decl_63, type, ( ge : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 15, character 0-42
tff(decl_64, type, ( gt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 16, character 0-36
tff(decl_65, type, ( out : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 17, character 0-41
tff(decl_66, type, ( midpoint : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 18, character 0-36
tff(decl_67, type, ( per : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 19, character 0-54
tff(decl_68, type, (
    perp_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 20, character 0-44
tff(decl_69, type, ( perp : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 21, character 0-42
tff(decl_70, type, ( ts : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 22, character 0-41
tff(decl_71, type, ( reflectP : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 23, character 0-42
tff(decl_72, type, ( os : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 24, character 0-47
tff(decl_73, type, ( inAngle : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 25, character 0-48
tff(decl_74, type, ( coplanar : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 26, character 0-58
tff(decl_75, type, (
    reflectL_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 27, character 0-48
tff(decl_76, type, ( reflectL : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 28, character 0-47
tff(decl_77, type, ( reflect : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 29, character 0-59
tff(decl_78, type, (
    congA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 30, character 0-57
tff(decl_79, type, (
    leA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 31, character 0-57
tff(decl_80, type, (
    ltA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 32, character 0-57
tff(decl_81, type, (
    gtA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 33, character 0-38
tff(decl_82, type, ( acute : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 34, character 0-39
tff(decl_83, type, ( obtuse : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 35, character 0-57
tff(decl_84, type, (
    geA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 36, character 0-43
tff(decl_85, type, ( par : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 37, character 0-50
tff(decl_86, type, ( par_strict : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 38, character 0-52
tff(decl_87, type, (
    inter : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 39, character 0-39
tff(decl_88, type, ( tarski_s_parallel_postulate : $o ) ).

%-- File './tarski_def.zf', line 40, character 0-40
tff(decl_89, type, ( decidability_of_intersection : $o ) ).

%-- File './tarski_def.zf', line 41, character 0-79
tff(decl_90, type, (
    sumA : ( point * point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 42, character 0-61
tff(decl_91, type, (
    triSumA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 43, character 0-58
tff(decl_92, type, (
    sams : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 44, character 0-48
tff(decl_93, type, ( saccheri : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 45, character 0-56
tff(decl_94, type, ( hypothesis_of_obtuse_saccheri_quadrilaterals : $o ) ).

%-- File './tarski_def.zf', line 51, character 0 to line 52, character 105
tff(hyp_64, axiom,
    (! [A: point , B: point , C: point] :
       (acute(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & ltA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 58, character 0 to line 59, character 114
tff(hyp_65, axiom,
    (! [A1: point , A2: point , A3: point , A4: point] :
       (bet_4(A1, A2, A3, A4)
       <=> (bet(A1, A2, A3)
           & (bet(A2, A3, A4) & (bet(A1, A3, A4) & bet(A1, A2, A4))))))).

%-- File './tarski_def.zf', line 62, character 0 to line 63, character 66
tff(hyp_66, axiom,
    (! [A: point , B: point , C: point] :
       (betS(A, B, C) <=> (bet(A, B, C) & ((~ (A = B)) & (~ (B = C))))))).

%-- File './tarski_def.zf', line 68, character 0 to line 69, character 75
tff(hyp_67, axiom,
    (! [A: point , B: point , C: point] :
       (col(A, B, C) <=> (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B)))))).

%-- File './tarski_def.zf', line 72, character 0 to line 73, character 111
tff(hyp_68, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1)
       <=> (cong(A, B, A1, B1) & (cong(A, C, A1, C1) & cong(B, C, B1, C1)))))).

%-- File './tarski_def.zf', line 77, character 0 to line 78, character 260
tff(hyp_69, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (congA(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (D = E))
               & ((~ (F = E))
                 & (? [A1: point , C1: point , D1: point , F1: point] :
                      (bet(B, A, A1)
                      & (cong(A, A1, E, D)
                        & (bet(B, C, C1)
                          & (cong(C, C1, E, F)
                            & (bet(E, D, D1)
                              & (cong(D, D1, B, A)
                                & (bet(E, F, F1)
                                  & (cong(F, F1, B, C)
                                    & cong(A1, C1, D1, F1))))))))))))))))).

%-- File './tarski_def.zf', line 81, character 0 to line 82, character 151
tff(hyp_70, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (coplanar(A, B, C, D)
       <=> (? [X: point] :
              ((col(A, B, X) & col(C, D, X))
              | ((col(A, C, X) & col(B, D, X))
                | (col(A, D, X) & col(B, C, X)))))))).

%-- File './tarski_def.zf', line 88, character 0 to line 89, character 138
tff(hyp_71, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (fsc(A, B, C, D, A1, B1, C1, D1)
       <=> (col(A, B, C)
           & (cong_3(A, B, C, A1, B1, C1)
             & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))).

%-- File './tarski_def.zf', line 94, character 0 to line 95, character 53
tff(hyp_72, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (ge(A, B, C, D) <=> le(C, D, A, B)))).

%-- File './tarski_def.zf', line 98, character 0 to line 99, character 53
tff(hyp_73, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (gt(A, B, C, D) <=> lt(C, D, A, B)))).

%-- File './tarski_def.zf', line 102, character 0 to line 103, character 67
tff(hyp_74, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (geA(A, B, C, D, E, F) <=> leA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 106, character 0 to line 107, character 67
tff(hyp_75, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (gtA(A, B, C, D, E, F) <=> ltA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 112, character 0 to line 113, character 166
tff(hyp_76, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ifsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, C, A1, C1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(C, D, C1, D1))))))))).

%-- File './tarski_def.zf', line 116, character 0 to line 117, character 127
tff(hyp_77, axiom,
    (! [P: point , A: point , B: point , C: point] :
       (inAngle(P, A, B, C)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (P = B))
               & (? [X: point] : (bet(A, X, C) & ((X = B) | out(B, X, P)))))))))).

%-- File './tarski_def.zf', line 120, character 0 to line 121, character 137
tff(hyp_78, axiom,
    (! [A1: point , A2: point , B1: point , B2: point , X: point] :
       (inter(A1, A2, B1, B2, X)
       <=> ((? [P: point] : (col(P, B1, B2) & (~ col(P, A1, A2))))
           & (col(A1, A2, X) & col(B1, B2, X)))))).

%-- File './tarski_def.zf', line 129, character 0 to line 130, character 90
tff(hyp_79, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (le(A, B, C, D)
       <=> (? [E: point] : (bet(C, E, D) & cong(A, B, C, E)))))).

%-- File './tarski_def.zf', line 133, character 0 to line 134, character 70
tff(hyp_80, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (lt(A, B, C, D) <=> (le(A, B, C, D) & (~ cong(A, B, C, D)))))).

%-- File './tarski_def.zf', line 137, character 0 to line 138, character 110
tff(hyp_81, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (leA(A, B, C, D, E, F)
       <=> (? [P: point] : (inAngle(P, D, E, F) & congA(A, B, C, D, E, P)))))).

%-- File './tarski_def.zf', line 141, character 0 to line 142, character 91
tff(hyp_82, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (ltA(A, B, C, D, E, F)
       <=> (leA(A, B, C, D, E, F) & (~ congA(A, B, C, D, E, F)))))).

%-- File './tarski_def.zf', line 148, character 0 to line 149, character 70
tff(hyp_83, axiom,
    (! [M: point , A: point , B: point] :
       (midpoint(M, A, B) <=> (bet(A, M, B) & cong(A, M, M, B))))).

%-- File './tarski_def.zf', line 155, character 0 to line 156, character 106
tff(hyp_84, axiom,
    (! [A: point , B: point , C: point] :
       (obtuse(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & gtA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 159, character 0 to line 160, character 166
tff(hyp_85, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ofsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, B, A1, B1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))))).

%-- File './tarski_def.zf', line 163, character 0 to line 164, character 89
tff(hyp_86, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (os(A, B, P, Q)
       <=> (? [R: point] : (ts(A, B, P, R) & ts(A, B, Q, R)))))).

%-- File './tarski_def.zf', line 167, character 0 to line 168, character 80
tff(hyp_87, axiom,
    (! [P: point , A: point , B: point] :
       (out(P, A, B)
       <=> ((~ (A = P)) & ((~ (B = P)) & (bet(P, A, B) | bet(P, B, A))))))).

%-- File './tarski_def.zf', line 173, character 0 to line 174, character 132
tff(hyp_88, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par_strict(A, B, C, D)
       <=> ((~ (A = B))
           & ((~ (C = D))
             & (coplanar(A, B, C, D)
               & (~ (? [X: point] : (col(X, A, B) & col(X, C, D)))))))))).

%-- File './tarski_def.zf', line 177, character 0 to line 178, character 107
tff(hyp_89, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par(A, B, C, D)
       <=> (par_strict(A, B, C, D)
           | ((~ (A = B)) & ((~ (C = D)) & (col(A, C, D) & col(B, C, D)))))))).

%-- File './tarski_def.zf', line 181, character 0 to line 182, character 95
tff(hyp_90, axiom,
    (! [A: point , B: point , C: point] :
       (per(A, B, C)
       <=> (? [C1: point] : (midpoint(B, C, C1) & cong(A, C, A, C1)))))).

%-- File './tarski_def.zf', line 185, character 0 to line 186, character 155
tff(hyp_91, axiom,
    (! [X: point , A: point , B: point , C: point , D: point] :
       (perp_at(X, A, B, C, D)
       <=> ((! [U: point , V: point] :
               (col(U, A, B) => (col(V, C, D) => per(U, X, V))))
           & ((~ (A = B)) & ((~ (C = D)) & (col(X, A, B) & col(X, C, D)))))))).

%-- File './tarski_def.zf', line 189, character 0 to line 190, character 84
tff(hyp_92, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (perp(A, B, C, D) <=> (? [X: point] : perp_at(X, A, B, C, D))))).

%-- File './tarski_def.zf', line 197, character 0 to line 198, character 62
tff(hyp_93, axiom,
    (! [A: point , A1: point , C: point] :
       (reflectP(A, A1, C) <=> midpoint(C, A1, A)))).

%-- File './tarski_def.zf', line 201, character 0 to line 202, character 115
tff(hyp_94, axiom,
    (! [M: point , P1: point , P: point , A: point , B: point] :
       (reflectL_at(M, P1, P, A, B)
       <=> (midpoint(M, P, P1) & col(A, B, M)
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 205, character 0 to line 206, character 128
tff(hyp_95, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflectL(P1, P, A, B)
       <=> ((? [X: point] : (midpoint(X, P, P1) & col(A, B, X)))
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 209, character 0 to line 210, character 106
tff(hyp_96, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflect(P1, P, A, B)
       <=> (((~ (A = B)) & reflectL(P1, P1, A, B))
           | ((A = B) & midpoint(A, P, P1)))))).

%-- File './tarski_def.zf', line 215, character 0 to line 216, character 140
tff(hyp_97, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point , G:
       point , H: point , I: point] :
       (sumA(A, B, C, D, E, F, G, H, I)
       <=> (? [J: point] :
              (congA(C, B, J, D, E, F)
              & ((~ os(B, C, A, J)) & congA(A, B, J, G, H, I))))))).

%-- File './tarski_def.zf', line 220, character 0 to line 221, character 101
tff(hyp_98, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (saccheri(A, B, C, D)
       <=> (per(B, A, D)
           & (per(A, D, C) & (cong(A, B, C, D) & os(A, D, B, C))))))).

%-- File './tarski_def.zf', line 224, character 0 to line 225, character 159
tff(hyp_99, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (sams(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((out(E, D, F) | (~ bet(A, B, C)))
             & (? [J: point] :
                  (congA(C, B, J, D, E, F)
                  & ((~ os(B, C, A, J)) & (~ ts(A, B, C, J)))))))))).

%-- File './tarski_def.zf', line 231, character 0 to line 232, character 130
tff(hyp_100, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (triSumA(A, B, C, D, E, F)
       <=> (? [G: point , H: point , I: point] :
              (sumA(A, B, C, B, C, A, G, H, I)
              & sumA(G, H, I, C, A, B, D, E, F)))))).

%-- File './tarski_def.zf', line 235, character 0 to line 236, character 115
tff(hyp_101, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (ts(A, B, P, Q)
       <=> ((~ col(P, A, B))
           & ((~ col(Q, A, B))
             & (? [T: point] : (col(T, A, B) & bet(P, T, Q)))))))).

%-- File './tarski_def.zf', line 241, character 0 to line 242, character 157
tff(hyp_102, axiom,
    (tarski_s_parallel_postulate
    <=> (! [A: point , B: point , C: point , D: point , T: point] :
           (bet(A, D, T)
           => (bet(B, C, D)
              => ((~ (A = D))
                 => (? [X: point , Y: point] :
                       (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y)))))))))).

%-- File './tarski_def.zf', line 244, character 0 to line 245, character 156
tff(hyp_103, axiom,
    (decidability_of_intersection
    <=> (! [A: point , B: point , C: point , D: point] :
           ((? [I: point] : (col(I, A, B) & col(I, C, D)))
           | (~ (? [I: point] : (col(I, A, B) & col(I, C, D)))))))).

%-- File './tarski_def.zf', line 247, character 0 to line 248, character 111
tff(hyp_104, axiom,
    (hypothesis_of_obtuse_saccheri_quadrilaterals
    <=> (! [A: point , B: point , C: point , D: point] :
           (saccheri(A, B, C, D) => obtuse(A, B, C))))).

%-- File './tarski_midpoint.zf', line 6, character 0-64
tff(hyp_105, axiom,
    (! [M: point , A: point , B: point] :
       (midpoint(M, A, B) => midpoint(M, B, A)))).

%-- File './tarski_midpoint.zf', line 9, character 0-42
tff(hyp_106, axiom, (! [A: point] : midpoint(A, A, A))).

%-- File './tarski_midpoint.zf', line 12, character 0-90
tff(hyp_107, axiom,
    (! [A: point , P: point , Q: point , P1: point , Q1: point] :
       (midpoint(A, P1, P) => (midpoint(A, Q1, Q) => cong(P, Q, P1, Q1))))).

%-- File './tarski_midpoint.zf', line 15, character 0-126
tff(hyp_108, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point , Z:
       point] :
       (midpoint(Z, A, D)
       => (midpoint(Z, B, E)
          => (midpoint(Z, C, F) => (midpoint(B, A, C) => midpoint(E, D, F))))))).

%-- File './tarski.zf', line 3, character 0-17
tff(decl_95, type, ( point : $tType ) ).

%-- File './tarski.zf', line 4, character 0-42
tff(decl_96, type, ( bet : ( point * point * point ) > $o ) ).

%-- File './tarski.zf', line 5, character 0-52
tff(decl_97, type, ( cong : ( point * point * point * point ) > $o ) ).

%-- File './tarski.zf', line 6, character 0-15
tff(decl_98, type, ( p_A_2 : point ) ).

%-- File './tarski.zf', line 7, character 0-15
tff(decl_99, type, ( p_B_2 : point ) ).

%-- File './tarski.zf', line 8, character 0-15
tff(decl_100, type, ( p_C_2 : point ) ).

%-- File './tarski.zf', line 10, character 0-42
tff(hyp_109, axiom, (! [A: point , B: point] : cong(A, B, B, A))).

%-- File './tarski.zf', line 11, character 0-81
tff(hyp_110, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (cong(A, B, C, D) => (cong(A, B, E, F) => cong(C, D, E, F))))).

%-- File './tarski.zf', line 12, character 0-53
tff(hyp_111, axiom,
    (! [A: point , B: point , C: point] : (cong(A, B, C, C) => (A = B)))).

%-- File './tarski.zf', line 13, character 0-78
tff(hyp_112, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (? [E: point] : (bet(A, B, E) & cong(B, E, C, D))))).

%-- File './tarski.zf', line 14, character 0-169
tff(hyp_113, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (cong(A, B, A1, B1)
       => (cong(B, C, B1, C1)
          => (cong(A, D, A1, D1)
             => (cong(B, D, B1, D1)
                => (bet(A, B, C)
                   => (bet(A1, B1, C1)
                      => ((~ (A = B)) => cong(C, D, C1, D1)))))))))).

%-- File './tarski.zf', line 15, character 0-46
tff(hyp_114, axiom, (! [A: point , B: point] : (bet(A, B, A) => (A = B)))).

%-- File './tarski.zf', line 16, character 0-105
tff(hyp_115, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (bet(A, P, C)
       => (bet(B, Q, C) => (? [X: point] : (bet(P, X, B) & bet(Q, X, A))))))).

%-- File './tarski.zf', line 18, character 0-56
tff(hyp_116, axiom,
    (~
    (bet(p_A_2, p_B_2, p_C_2)
    | (bet(p_B_2, p_C_2, p_A_2) | bet(p_C_2, p_A_2, p_B_2))))).

%-- File './tarski.zf', line 19, character 0-127
tff(hyp_117, axiom,
    (! [A: point , B: point , C: point , P: point , Q: point] :
       (cong(A, P, A, Q)
       => (cong(B, P, B, Q)
          => (cong(C, P, C, Q)
             => ((~ (P = Q))
                => (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B))))))))).

%-- File './tarski.zf', line 20, character 0-127
tff(hyp_118, axiom,
    (! [A: point , B: point , C: point , D: point , T: point] :
       (? [X: point , Y: point] :
          (bet(A, D, T)
          => (bet(B, D, C)
             => ((~ (A = D))
                => (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y))))))))).

%-- File './tarski.zf', line 22, character 0-41
tff(hyp_119, axiom, (! [A: point , B: point] : ((A = B) | (~ (A = B))))).

%-- File './tarski_def.zf', line 5, character 0-42
tff(decl_101, type, ( col : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 6, character 0-88
tff(decl_102, type, (
    ofsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 7, character 0-72
tff(decl_103, type, (
    cong_3 : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 8, character 0-45
tff(decl_104, type, ( bet_4 : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 9, character 0-37
tff(decl_105, type, ( betS : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 10, character 0-88
tff(decl_106, type, (
    ifsc : ( point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 11, character 0-87
tff(decl_107, type, (
    fsc : ( point * point * point * point * point * point * point * point ) >
          $o ) ).

%-- File './tarski_def.zf', line 12, character 0-42
tff(decl_108, type, ( le : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 13, character 0-42
tff(decl_109, type, ( lt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 14, character 0-42
tff(decl_110, type, ( ge : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 15, character 0-42
tff(decl_111, type, ( gt : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 16, character 0-36
tff(decl_112, type, ( out : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 17, character 0-41
tff(decl_113, type, ( midpoint : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 18, character 0-36
tff(decl_114, type, ( per : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 19, character 0-54
tff(decl_115, type, (
    perp_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 20, character 0-44
tff(decl_116, type, ( perp : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 21, character 0-42
tff(decl_117, type, ( ts : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 22, character 0-41
tff(decl_118, type, ( reflectP : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 23, character 0-42
tff(decl_119, type, ( os : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 24, character 0-47
tff(decl_120, type, ( inAngle : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 25, character 0-48
tff(decl_121, type, ( coplanar : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 26, character 0-58
tff(decl_122, type, (
    reflectL_at : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 27, character 0-48
tff(decl_123, type, ( reflectL : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 28, character 0-47
tff(decl_124, type, ( reflect : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 29, character 0-59
tff(decl_125, type, (
    congA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 30, character 0-57
tff(decl_126, type, (
    leA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 31, character 0-57
tff(decl_127, type, (
    ltA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 32, character 0-57
tff(decl_128, type, (
    gtA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 33, character 0-38
tff(decl_129, type, ( acute : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 34, character 0-39
tff(decl_130, type, ( obtuse : ( point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 35, character 0-57
tff(decl_131, type, (
    geA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 36, character 0-43
tff(decl_132, type, ( par : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 37, character 0-50
tff(decl_133, type, ( par_strict : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 38, character 0-52
tff(decl_134, type, (
    inter : ( point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 39, character 0-39
tff(decl_135, type, ( tarski_s_parallel_postulate : $o ) ).

%-- File './tarski_def.zf', line 40, character 0-40
tff(decl_136, type, ( decidability_of_intersection : $o ) ).

%-- File './tarski_def.zf', line 41, character 0-79
tff(decl_137, type, (
    sumA : ( point * point * point * point * point * point * point * point
           * point ) > $o ) ).

%-- File './tarski_def.zf', line 42, character 0-61
tff(decl_138, type, (
    triSumA : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 43, character 0-58
tff(decl_139, type, (
    sams : ( point * point * point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 44, character 0-48
tff(decl_140, type, ( saccheri : ( point * point * point * point ) > $o ) ).

%-- File './tarski_def.zf', line 45, character 0-56
tff(decl_141, type, ( hypothesis_of_obtuse_saccheri_quadrilaterals : $o ) ).

%-- File './tarski_def.zf', line 51, character 0 to line 52, character 105
tff(hyp_120, axiom,
    (! [A: point , B: point , C: point] :
       (acute(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & ltA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 58, character 0 to line 59, character 114
tff(hyp_121, axiom,
    (! [A1: point , A2: point , A3: point , A4: point] :
       (bet_4(A1, A2, A3, A4)
       <=> (bet(A1, A2, A3)
           & (bet(A2, A3, A4) & (bet(A1, A3, A4) & bet(A1, A2, A4))))))).

%-- File './tarski_def.zf', line 62, character 0 to line 63, character 66
tff(hyp_122, axiom,
    (! [A: point , B: point , C: point] :
       (betS(A, B, C) <=> (bet(A, B, C) & ((~ (A = B)) & (~ (B = C))))))).

%-- File './tarski_def.zf', line 68, character 0 to line 69, character 75
tff(hyp_123, axiom,
    (! [A: point , B: point , C: point] :
       (col(A, B, C) <=> (bet(A, B, C) | (bet(B, C, A) | bet(C, A, B)))))).

%-- File './tarski_def.zf', line 72, character 0 to line 73, character 111
tff(hyp_124, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1)
       <=> (cong(A, B, A1, B1) & (cong(A, C, A1, C1) & cong(B, C, B1, C1)))))).

%-- File './tarski_def.zf', line 77, character 0 to line 78, character 260
tff(hyp_125, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (congA(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (D = E))
               & ((~ (F = E))
                 & (? [A1: point , C1: point , D1: point , F1: point] :
                      (bet(B, A, A1)
                      & (cong(A, A1, E, D)
                        & (bet(B, C, C1)
                          & (cong(C, C1, E, F)
                            & (bet(E, D, D1)
                              & (cong(D, D1, B, A)
                                & (bet(E, F, F1)
                                  & (cong(F, F1, B, C)
                                    & cong(A1, C1, D1, F1))))))))))))))))).

%-- File './tarski_def.zf', line 81, character 0 to line 82, character 151
tff(hyp_126, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (coplanar(A, B, C, D)
       <=> (? [X: point] :
              ((col(A, B, X) & col(C, D, X))
              | ((col(A, C, X) & col(B, D, X))
                | (col(A, D, X) & col(B, C, X)))))))).

%-- File './tarski_def.zf', line 88, character 0 to line 89, character 138
tff(hyp_127, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (fsc(A, B, C, D, A1, B1, C1, D1)
       <=> (col(A, B, C)
           & (cong_3(A, B, C, A1, B1, C1)
             & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))).

%-- File './tarski_def.zf', line 94, character 0 to line 95, character 53
tff(hyp_128, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (ge(A, B, C, D) <=> le(C, D, A, B)))).

%-- File './tarski_def.zf', line 98, character 0 to line 99, character 53
tff(hyp_129, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (gt(A, B, C, D) <=> lt(C, D, A, B)))).

%-- File './tarski_def.zf', line 102, character 0 to line 103, character 67
tff(hyp_130, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (geA(A, B, C, D, E, F) <=> leA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 106, character 0 to line 107, character 67
tff(hyp_131, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (gtA(A, B, C, D, E, F) <=> ltA(D, E, F, A, B, C)))).

%-- File './tarski_def.zf', line 112, character 0 to line 113, character 166
tff(hyp_132, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ifsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, C, A1, C1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(C, D, C1, D1))))))))).

%-- File './tarski_def.zf', line 116, character 0 to line 117, character 127
tff(hyp_133, axiom,
    (! [P: point , A: point , B: point , C: point] :
       (inAngle(P, A, B, C)
       <=> ((~ (A = B))
           & ((~ (C = B))
             & ((~ (P = B))
               & (? [X: point] : (bet(A, X, C) & ((X = B) | out(B, X, P)))))))))).

%-- File './tarski_def.zf', line 120, character 0 to line 121, character 137
tff(hyp_134, axiom,
    (! [A1: point , A2: point , B1: point , B2: point , X: point] :
       (inter(A1, A2, B1, B2, X)
       <=> ((? [P: point] : (col(P, B1, B2) & (~ col(P, A1, A2))))
           & (col(A1, A2, X) & col(B1, B2, X)))))).

%-- File './tarski_def.zf', line 129, character 0 to line 130, character 90
tff(hyp_135, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (le(A, B, C, D)
       <=> (? [E: point] : (bet(C, E, D) & cong(A, B, C, E)))))).

%-- File './tarski_def.zf', line 133, character 0 to line 134, character 70
tff(hyp_136, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (lt(A, B, C, D) <=> (le(A, B, C, D) & (~ cong(A, B, C, D)))))).

%-- File './tarski_def.zf', line 137, character 0 to line 138, character 110
tff(hyp_137, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (leA(A, B, C, D, E, F)
       <=> (? [P: point] : (inAngle(P, D, E, F) & congA(A, B, C, D, E, P)))))).

%-- File './tarski_def.zf', line 141, character 0 to line 142, character 91
tff(hyp_138, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (ltA(A, B, C, D, E, F)
       <=> (leA(A, B, C, D, E, F) & (~ congA(A, B, C, D, E, F)))))).

%-- File './tarski_def.zf', line 148, character 0 to line 149, character 70
tff(hyp_139, axiom,
    (! [M: point , A: point , B: point] :
       (midpoint(M, A, B) <=> (bet(A, M, B) & cong(A, M, M, B))))).

%-- File './tarski_def.zf', line 155, character 0 to line 156, character 106
tff(hyp_140, axiom,
    (! [A: point , B: point , C: point] :
       (obtuse(A, B, C)
       <=> (? [A1: point , B1: point , C1: point] :
              (per(A1, B1, C1) & gtA(A, B, C, A1, B1, C1)))))).

%-- File './tarski_def.zf', line 159, character 0 to line 160, character 166
tff(hyp_141, axiom,
    (! [A: point , B: point , C: point , D: point , A1: point , B1: point
       , C1: point , D1: point] :
       (ofsc(A, B, C, D, A1, B1, C1, D1)
       <=> (bet(A, B, C)
           & (bet(A1, B1, C1)
             & (cong(A, B, A1, B1)
               & (cong(B, C, B1, C1)
                 & (cong(A, D, A1, D1) & cong(B, D, B1, D1))))))))).

%-- File './tarski_def.zf', line 163, character 0 to line 164, character 89
tff(hyp_142, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (os(A, B, P, Q)
       <=> (? [R: point] : (ts(A, B, P, R) & ts(A, B, Q, R)))))).

%-- File './tarski_def.zf', line 167, character 0 to line 168, character 80
tff(hyp_143, axiom,
    (! [P: point , A: point , B: point] :
       (out(P, A, B)
       <=> ((~ (A = P)) & ((~ (B = P)) & (bet(P, A, B) | bet(P, B, A))))))).

%-- File './tarski_def.zf', line 173, character 0 to line 174, character 132
tff(hyp_144, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par_strict(A, B, C, D)
       <=> ((~ (A = B))
           & ((~ (C = D))
             & (coplanar(A, B, C, D)
               & (~ (? [X: point] : (col(X, A, B) & col(X, C, D)))))))))).

%-- File './tarski_def.zf', line 177, character 0 to line 178, character 107
tff(hyp_145, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (par(A, B, C, D)
       <=> (par_strict(A, B, C, D)
           | ((~ (A = B)) & ((~ (C = D)) & (col(A, C, D) & col(B, C, D)))))))).

%-- File './tarski_def.zf', line 181, character 0 to line 182, character 95
tff(hyp_146, axiom,
    (! [A: point , B: point , C: point] :
       (per(A, B, C)
       <=> (? [C1: point] : (midpoint(B, C, C1) & cong(A, C, A, C1)))))).

%-- File './tarski_def.zf', line 185, character 0 to line 186, character 155
tff(hyp_147, axiom,
    (! [X: point , A: point , B: point , C: point , D: point] :
       (perp_at(X, A, B, C, D)
       <=> ((! [U: point , V: point] :
               (col(U, A, B) => (col(V, C, D) => per(U, X, V))))
           & ((~ (A = B)) & ((~ (C = D)) & (col(X, A, B) & col(X, C, D)))))))).

%-- File './tarski_def.zf', line 189, character 0 to line 190, character 84
tff(hyp_148, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (perp(A, B, C, D) <=> (? [X: point] : perp_at(X, A, B, C, D))))).

%-- File './tarski_def.zf', line 197, character 0 to line 198, character 62
tff(hyp_149, axiom,
    (! [A: point , A1: point , C: point] :
       (reflectP(A, A1, C) <=> midpoint(C, A1, A)))).

%-- File './tarski_def.zf', line 201, character 0 to line 202, character 115
tff(hyp_150, axiom,
    (! [M: point , P1: point , P: point , A: point , B: point] :
       (reflectL_at(M, P1, P, A, B)
       <=> (midpoint(M, P, P1) & col(A, B, M)
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 205, character 0 to line 206, character 128
tff(hyp_151, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflectL(P1, P, A, B)
       <=> ((? [X: point] : (midpoint(X, P, P1) & col(A, B, X)))
           & (perp(A, B, P, P1) | (P = P1)))))).

%-- File './tarski_def.zf', line 209, character 0 to line 210, character 106
tff(hyp_152, axiom,
    (! [P1: point , P: point , A: point , B: point] :
       (reflect(P1, P, A, B)
       <=> (((~ (A = B)) & reflectL(P1, P1, A, B))
           | ((A = B) & midpoint(A, P, P1)))))).

%-- File './tarski_def.zf', line 215, character 0 to line 216, character 140
tff(hyp_153, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point , G:
       point , H: point , I: point] :
       (sumA(A, B, C, D, E, F, G, H, I)
       <=> (? [J: point] :
              (congA(C, B, J, D, E, F)
              & ((~ os(B, C, A, J)) & congA(A, B, J, G, H, I))))))).

%-- File './tarski_def.zf', line 220, character 0 to line 221, character 101
tff(hyp_154, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (saccheri(A, B, C, D)
       <=> (per(B, A, D)
           & (per(A, D, C) & (cong(A, B, C, D) & os(A, D, B, C))))))).

%-- File './tarski_def.zf', line 224, character 0 to line 225, character 159
tff(hyp_155, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (sams(A, B, C, D, E, F)
       <=> ((~ (A = B))
           & ((out(E, D, F) | (~ bet(A, B, C)))
             & (? [J: point] :
                  (congA(C, B, J, D, E, F)
                  & ((~ os(B, C, A, J)) & (~ ts(A, B, C, J)))))))))).

%-- File './tarski_def.zf', line 231, character 0 to line 232, character 130
tff(hyp_156, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (triSumA(A, B, C, D, E, F)
       <=> (? [G: point , H: point , I: point] :
              (sumA(A, B, C, B, C, A, G, H, I)
              & sumA(G, H, I, C, A, B, D, E, F)))))).

%-- File './tarski_def.zf', line 235, character 0 to line 236, character 115
tff(hyp_157, axiom,
    (! [A: point , B: point , P: point , Q: point] :
       (ts(A, B, P, Q)
       <=> ((~ col(P, A, B))
           & ((~ col(Q, A, B))
             & (? [T: point] : (col(T, A, B) & bet(P, T, Q)))))))).

%-- File './tarski_def.zf', line 241, character 0 to line 242, character 157
tff(hyp_158, axiom,
    (tarski_s_parallel_postulate
    <=> (! [A: point , B: point , C: point , D: point , T: point] :
           (bet(A, D, T)
           => (bet(B, C, D)
              => ((~ (A = D))
                 => (? [X: point , Y: point] :
                       (bet(A, B, X) & (bet(A, C, Y) & bet(X, T, Y)))))))))).

%-- File './tarski_def.zf', line 244, character 0 to line 245, character 156
tff(hyp_159, axiom,
    (decidability_of_intersection
    <=> (! [A: point , B: point , C: point , D: point] :
           ((? [I: point] : (col(I, A, B) & col(I, C, D)))
           | (~ (? [I: point] : (col(I, A, B) & col(I, C, D)))))))).

%-- File './tarski_def.zf', line 247, character 0 to line 248, character 111
tff(hyp_160, axiom,
    (hypothesis_of_obtuse_saccheri_quadrilaterals
    <=> (! [A: point , B: point , C: point , D: point] :
           (saccheri(A, B, C, D) => obtuse(A, B, C))))).

%-- File './tarski_cong.zf', line 6, character 0-62
tff(hyp_161, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(B, A, D, C)))).

%-- File './tarski_cong.zf', line 9, character 0-62
tff(hyp_162, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(C, D, B, A)))).

%-- File './tarski_cong.zf', line 12, character 0-62
tff(hyp_163, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(D, C, A, B)))).

%-- File './tarski_cong.zf', line 15, character 0-62
tff(hyp_164, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(D, C, B, A)))).

%-- File './tarski_cong.zf', line 18, character 0-42
tff(hyp_165, axiom, (! [A: point , B: point] : cong(A, A, B, B))).

%-- File './tarski_cong.zf', line 21, character 0-62
tff(hyp_166, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(B, A, C, D)))).

%-- File './tarski_cong.zf', line 24, character 0-62
tff(hyp_167, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(A, B, D, C)))).

%-- File './tarski_cong.zf', line 27, character 0-62
tff(hyp_168, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(C, D, A, B)))).

%-- File './tarski_cong.zf', line 30, character 0-42
tff(hyp_169, axiom, (! [A: point , B: point] : cong(A, B, A, B))).

%-- File './tarski_cong.zf', line 33, character 0-82
tff(hyp_170, axiom,
    (! [A: point , B: point , C: point , D: point , E: point , F: point] :
       (cong(A, B, C, D) => (cong(C, D, E, F) => cong(A, B, E, F))))).

%-- File './tarski_cong.zf', line 36, character 0-64
tff(hyp_171, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(B, A, C, D))))).

%-- File './tarski_cong.zf', line 39, character 0-64
tff(hyp_172, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(A, B, D, C))))).

%-- File './tarski_cong.zf', line 42, character 0-64
tff(hyp_173, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(B, A, D, C))))).

%-- File './tarski_cong.zf', line 45, character 0-64
tff(hyp_174, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(C, D, A, B))))).

%-- File './tarski_cong.zf', line 48, character 0-64
tff(hyp_175, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(D, C, A, B))))).

%-- File './tarski_cong.zf', line 51, character 0-64
tff(hyp_176, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(C, D, B, A))))).

%-- File './tarski_cong.zf', line 54, character 0-64
tff(hyp_177, axiom,
    (! [A: point , B: point , C: point , D: point] :
       ((~ cong(A, B, C, D)) => (~ cong(D, C, B, A))))).

%-- File './tarski_cong.zf', line 58, character 0-87
tff(hyp_178, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1) => cong_3(A1, B1, C1, A, B, C)))).

%-- File './tarski_cong.zf', line 61, character 0-87
tff(hyp_179, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1) => cong_3(B, A, C, B1, A1, C1)))).

%-- File './tarski_cong.zf', line 64, character 0-87
tff(hyp_180, axiom,
    (! [A: point , B: point , C: point , A1: point , B1: point , C1: point] :
       (cong_3(A, B, C, A1, B1, C1) => cong_3(A, C, B, A1, C1, B1)))).

%-- File './tarski_cong.zf', line 67, character 0-133
tff(hyp_181, axiom,
    (! [A0: point , B0: point , C0: point , A1: point , B1: point , C1: point
       , A2: point , B2: point , C2: point] :
       (cong_3(A0, B0, C0, A1, B1, C1)
       => (cong_3(A1, B1, C1, A2, B2, C2) => cong_3(A0, B0, C0, A2, B2, C2))))).

%-- File './tarski_cong.zf', line 70, character 0-66
tff(hyp_182, axiom,
    (! [A: point , B: point , C: point , D: point] :
       (cong(A, B, C, D) => cong(A, B, C, D)))).

%-- File './tarski_cong.zf', line 73, character 0-62
tff(hyp_183, axiom,
    (! [A: point , B: point , C: point] :
       (midpoint(B, A, C) => cong(A, B, B, C)))).

%-- File './tarski_cong.zf', line 76, character 0-51
tff(hyp_184, axiom,
    (! [A: point , C: point , D: point] : (cong(A, A, C, D) => (C = D)))).

%-- File './17_16.zf', line 8, character 0-90
tff(hyp_185, axiom,
    (! [A: point , P: point , Q: point , P1: point , Q1: point] :
       (midpoint(A, P1, P) => (midpoint(A, Q1, Q) => cong(P, Q, P1, Q1))))).

%-- Implicitly declared
tff(goal_1, conjecture,
    (! [P: point , Q: point , R: point , S: point , P1: point , Q1: point
       , S1: point , R1: point , A: point] :
       (midpoint(A, P, P1)
       => (midpoint(A, Q, Q1)
          => (midpoint(A, R, R1)
             => (midpoint(A, S, S1)
                => (cong(P, Q, R, S) => cong(P1, Q1, R1, S1)))))))).

